### ISSUE TITLE
v10 version of action quits with success while not doing anything

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#108]
Hello!

I'm upgrading my workflow from v3 to v10 and running into a bit of an issue - the action runs and quits with success while not having done anything. What could be wrong?

Here is the workflow run with debugging enabled: https://github.com/Mudlet/Mudlet/actions/runs/4744395516/jobs/8425405550#step:21:1

**Comment by lukka** [comment]
@vadi2  thanks for reporting this! This is clearly a bug because the action should have triggered an error since it has not done anything as no input has been provided. 

The reason is that from `v10` the action requires usage of the CMakePresets.json file, you may read the [quickstart](https://github.com/lukka/run-cmake#quickstart-with-instructions) to see an example.

**Comment by vadi2** [comment]
The documentation made it seem like CMakePresets.json was optional. No way without one?

**Comment by lukka** [comment]
@vadi2 yes, `run-cmake@v10` requires at least one preset to be specified and the usage of CMakePresets.json is mandatory. In your case the action should have triggered an error indeed.

**Comment by lukka** [comment]
@vadi2 updated the docs and added an error when CMakePresets.json is not used.
