### ISSUE TITLE
Add option `allow-failure`

### ISSUE THREAD

**Issue by LecrisUT** [lukka/run-cmake#132]
Since overwriting a job's output is still impossible [^1], it would be nice to add a `allow-failure` similar to [`fail_ci_if_error`](https://github.com/codecov/codecov-action#arguments) on codecov and other such actions. Ideally it would have two variants, `allow-failure` and `allow-test-failure` in order to overwrite the overall/any failure of `cmake`, or specifically of `ctest`, but unfortunately the latter is incompatible with workflow presets (but things might change [^2][^3]).

I will try to make a PR to add this feature, but similar to #130, I could use some help setting up the local environment

[^1]: https://github.com/actions/runner/issues/662
[^2]: https://gitlab.kitware.com/cmake/cmake/-/issues/25475
[^3]: https://gitlab.kitware.com/cmake/cmake/-/issues/25476

**Comment by lukka** [comment]
@LecrisUT if I understood correctly you'd like to add a feature that makes the `run-cmake` action to not fail when cmake fails (i.e. when it returns an error different than 0).

I'd suggest to implement such logic in the tooling itself (e.g. `cmake` or `ctest`) or use GH features like `output variables` (e.g. the exit code of cmake/ctest could be set in an output variable by `run-cmake`) along with `continue-on-error: true`, and put the logic in a subsequent step in the workflow itself to decide whether to fail/not-fail the workflow.

Note that the [fail-if-ic-error](https://github.com/codecov/codecov-action#arguments) is useful to avoid failing the workflow when "Codecov runs into errors during upload.", which is a way to fail the workflow when the cause is external, which makes sense but also it is just a workaround rather than a fix of the root of the problem.

If you are willing to create a PR, you are welcome to proceed forward. I can certainly help with the review of the PR.

**Comment by LecrisUT** [comment]
I have experimented a bit, and it's worth pointing out that there are `job.continue-on-error` and `steps[*].continue-on-error`. The latter is the equivalent of this `allow-failure`. Not sure where it would be good to document, I have it documented in my cmake-template.
