### ISSUE TITLE
Support for annotations

### ISSUE THREAD

**Issue by vadi2** [lukka/run-cmake#17]
Would it be possible to support [annotations](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks) with the action?

Any warnings right now are pretty hidden deep inside the workflow -> job -> vcpkg step -> run vcpkg.

![Selection_564](https://user-images.githubusercontent.com/110988/80282845-f3a49780-8713-11ea-9d2f-b393fe4c9bc4.png)

Just a quality of life improvement.

**Comment by lukka** [comment]
@vadi2 this is a great suggestion indeed: is adding a [problem matcher](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers) going to help?
I think a different set of matchers could be enabled: 
 - one set for CMake used at configuration time;
 - one used when building, this requires understanding which compiler is being used (i.e. msvc vs gcc/clang);
 
Is there any other set of matchers that could be added?

**Comment by vadi2** [comment]
I believe that covers them all!

**Comment by lukka** [comment]
since the limitation of `fromPath`, the annotation for CMake works only if the CMakeLists.txt file is located on the root of the repository: https://github.com/actions/runner/issues/461

Unless I come up with a different solution, the CMake annotation could be enabled only when the CMakeLists.txt is in the root of the repo.

**Comment by vadi2** [comment]
Sounds OK to me. Ours is at root: https://github.com/Mudlet/Mudlet
