### ISSUE TITLE
Changes in environment variables

### ISSUE THREAD

**Issue by magnesj** [lukka/run-cmake#8]
Hi,

We have been using parts of your build system, and we find it easy to use and maintain. Last week, GitHub updated the CI servers, and our build started to break. The reason was that the path to Python executable was no longer available. 

It seems to me that the propagation of path from the CI server to the build process in Visual Studio is not working as expected now.

Here is a reference to a build that ran without issues before the upgrade last week. As you can see, python is no longer available from the build job in Visual Studio. 

**Failing build**
https://github.com/OPM/ResInsight/runs/536161809?check_suite_focus=true

**Successful build**
https://github.com/OPM/ResInsight/runs/533332280?check_suite_focus=true

As a workaround we will use command line config of CMake directly.

Any clue why this happens?

Regards
Magne

**Comment by lukka** [comment]
I just released v1 version of `run-cmake` and `run-vcpkg`, they spawn any process (e.g. cmake/git/vcpkg) under the default shell, this may help in fixing this. 
To understand exactly what the issue is I usually set `ACTIONS_STEP_DEBUG` to `true` in the secrets of the repository (under Settings) and then I can follow and trace the whole execution. 

I started such build with full debug output on my fork in [ci_actions_v1 branch](https://github.com/OPM/ResInsight/compare/dev...lukka:ci_actions_v1) where I use the v1 version of the actions. I will take a look at the log to understand how to fix it (if not fixed already).

**Comment by lukka** [comment]
@magnesj the build failed again in the same way. [CMake is started with the following PATH env var](https://github.com/lukka/ResInsight/runs/544550450#step:9:469):

```
PATH=[cut....] 
C:\\hostedtoolcache\\windows\\**Python**\\**3.7.6**\\x64\\Scripts;
C:\\hostedtoolcache\\windows\\**Python**\\**3.7.6**\\x64;
[....]
```

is that the expected path for Python? I have not spot what is possibly wrong yet.

**Comment by magnesj** [comment]
> @magnesj the build failed again in the same way. [CMake is started with the following PATH env var](https://github.com/lukka/ResInsight/runs/544550450#step:9:469):
> 
> ```
> PATH=[cut....] 
> C:\\hostedtoolcache\\windows\\**Python**\\**3.7.6**\\x64\\Scripts;
> C:\\hostedtoolcache\\windows\\**Python**\\**3.7.6**\\x64;
> [....]
> ```
> 
> is that the expected path for Python? I have not spot what is possibly wrong yet.

I think this path is correct, but I do not understand how this path is different for the job launching python.

**Comment by lukka** [comment]
Found the culprit: since VS 16.5, the `Microsoft.Cpp.Default.props`  property file contains a rule that says "strip `PATH` to bare minimum when running inside a Developer Command Prompt of Visual Studio". This is happening when using `run-cmake` because when running CMake.exe on Windows the action setups the shell environment as the DevCmdPrompt would set it up.  

The MSBuild rule is inside Microsoft.Cpp.Default.props:  `<PATH Condition="'$(__VSCMD_PREINIT_PATH)' != ''">$(__VSCMD_PREINIT_PATH)</PATH>`. 

There are various fixes/workaround here for `run-cmake`:
  * The solution is to avoid changing the environment in any way when using the VS project file generator of CMake;
  *  A workaround for the `run-cmake` action is to to avoid set `__VSCMD_PRENINIT_PATH`, or  `VSCMD_VER` in order to alleviate the problem;

For consumers of `run-cmake`:
  * do not use VS generators;
  * use Ninja (it is a benefit in speed and in 'same tool on any platform');
  * there is also Ninja Multi Config that should already work properly with the `run-cmake` action; "it should" because there are not automatic tests on it yet;
