### ISSUE TITLE
Option for passing additional arguments to cmake

### ISSUE THREAD

**Issue by Kicer86** [lukka/run-cmake#85]
It would be useful to me if I could pass additional arguments to CMake (not specified in present file). 
In my case I'd like to set CMAKE_C(XX)_COMPILER_LAUNCHER variables.

**Comment by lukka** [comment]
@Kicer86 I think that is just an environment variable that you could set in the [CMakePresets.json](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) file. 

Note that it is an intentional choice to have the build process entirely driven by the CMakePresets.json content, and anything external and not specified in the file would defeat the purpose of the file itself, i.e. reproducible/identical builds by developer and CI machines.

**Comment by lukka** [comment]
@Kicer86 please note you can define the environment variable in the CMakePresets.json file itself, like this:

```json
 "environment": {
        "MY_ENVIRONMENT_VARIABLE": "Test",
        "PATH": "$env{HOME}/ninja/bin:$penv{PATH}"
      },
```

In practice what I am suggesting is to let the build be driven entirely by the content of CMakePresets.json file, and nothing else.

Do not hesitate to report back your findings and your feedback about this.

**Comment by lukka** [comment]
@Kicer86 does my last comment make sense and helped you? Please follow up if this issue is not solved, thanks!
